[tool.poetry]
name = "gadget"
version = "0.0.1-rc"
description = ""
authors = ["Ds Team <ds@team.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
